# Generated by Django 2.2.3 on 2019-07-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='deskripsi',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
