# Generated by Django 2.2.3 on 2019-07-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190725_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='test',
            field=models.SlugField(default=''),
        ),
    ]
